version: "3"

services:
  eagles-cms:
    build: .
    ports:
    - "3333:1337"
    volumes:
    - /data/eagleslinedancers/db:/srv/app/.tmp
    - /data/eagleslinedancers/public/uploads:/srv/app/public/uploads
