name: Deploy CMS

on:
  workflow_dispatch:

jobs:
  deploy-cms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Key
        shell: bash
        run: |
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ./cms/id_rsa
          chmod 600 ./cms/id_rsa
          echo "${{ secrets.DEPLOY_KNOWN_HOSTS }}" > ./cms/ssh_known_hosts
      - name: Docker Deploy
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: ${{ secrets.DOCKER_HOST }}
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          stack_file_name: ./cms/docker-compose.yml
          pull_images_first: true
          args: up -d --build
