name: Fetch data

on: 
  repository_dispatch:
    types: [fetch]

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - shell: bash
      run: |
        curl -X POST -d '{"username":"GitHub","content":"Testnachricht"}' -H "Content-Type: application/json" https://discord.com/api/webhooks/902909348056035368/h6qTVOqTNYX1_pVb4K0ZXAz_Zn7xYy_srXpH0jpc1UuEPi4Nn4F95ngv7kH2fmkcOfJb
